image: lorisleiva/laravel-docker:latest

.init_ssh: &init_ssh |
  eval $(ssh-agent -s)
  echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add - > /dev/null
  mkdir -p ~/.ssh
  chmod 700 ~/.ssh
  [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

# Replace the last line with the following lines if you'd rather
# leave StrictHostKeyChecking enabled (replace yourdomain.com):
#
#  ssh-keyscan yourdomain.com >> ~/.ssh/known_hosts
#  chmod 644 ~/.ssh/known_hosts
  
.change_file_permissions: &change_file_permissions |
  find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;    
  find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;
    
composer:
  stage: build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/
  script:
      - composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - cp .env.example .env
      - php artisan key:generate
  artifacts:
    expire_in: 1 day
    paths:
      - vendor/
      - .env

# npm:
#   stage: build
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}-npm
#     paths:
#       - node_modules/
#   script:
#       - npm install
#       - npm run production
#   artifacts:
#     expire_in: 1 month
#     paths:
#       - node_modules/
#       - public/css/
#       - public/js/

codestyle:
  stage: test
  dependencies: []
  script:
    - phpcs --standard=PSR2 --extensions=php --ignore=app/Support/helpers.php app
    
# phpunit:
#   stage: test
#   dependencies:
#     - composer
#   script:
#     - phpunit --coverage-text --colors=never

staging:
  stage: deploy
  services:
    - docker:dind
  script:
    - *init_ssh
    - ssh -T -o StrictHostKeyChecking=no gitlabci@beta.thetrifactory.com <<'ENDSSH'
    - cd git
    - cd thetrifactory.com
    - git reset --hard
    - git checkout develop
    - git pull
    - cp .env.example .env    
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - *change_file_permissions
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 php artisan deploy localhost
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 /bin/bash -c "cd /code/current && php artisan nova:publish --force"
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 /bin/bash -c "cd /code/current && php artisan telescope:publish --force"
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 chmod -R 777 /code/shared/storage
  environment:
    name: staging
    url: https://beta.thetrifactory.com
  only:
    - develop
  
production:
  stage: deploy
  services:
    - docker:dind
  script:
    - *init_ssh
    - ssh -T -o StrictHostKeyChecking=no gitlabci@beta.thetrifactory.com <<'ENDSSH'
    - cd git
    - cd thetrifactory.com
    - git reset --hard
    - git checkout master
    - git pull
    - cp .env.example .env
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
    - *change_file_permissions
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 php artisan deploy localhost
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 /bin/bash -c "cd /code/current && php artisan nova:publish --force"
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 /bin/bash -c "cd /code/current && php artisan telescope:publish --force"
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 chmod -R 777 /code/shared/storage
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 sudo chmod 775 -R storage
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 sudo chown -R $USER:www-data storage
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 sudo chmod 775 -R bootstrap/cache
    - docker run --network=trifactory_network -v trifactory_code:/code -v /home/gitlabci/.ssh:/root/.ssh -v /home/gitlabci/git/thetrifactory.com:/var/www/html breadcrumbsstudio/laravel-gitlab-ci:1.0 sudo chown -R $USER:www-data bootstrap/cache
  environment:
    name: production
    url: https://www.thetrifactory.com
  when: manual
  only:
   - master